name: Build for CI

on:
  push:
    branches:
      - github-workflow-ci
  pull_request:
    branches:
      - github-workflow-ci
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-f34-x64:
    runs-on: ubuntu-20.04
    container: vathpela/efi-ci:f34
    name: A job to test building on Fedora 34
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do the build
        run: make
                  PREFIX=/usr
                  LIBDIR=/usr/lib64
                  DESTDIR=/destdir
                  EFIDIR=test
                  ENABLE_HTTPBOOT=true
                  ENABLE_SHIM_HASH=true
                  clean all
        id: build
      - name: Install in /destdir
        run: make
                  PREFIX=/usr
                  LIBDIR=/usr/lib64
                  DESTDIR=/destdir
                  EFIDIR=test
                  ENABLE_HTTPBOOT=true
                  ENABLE_SHIM_HASH=true
                  install
        id: install
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: shim
#          path: |
#            /destdir
